server:
  servlet:
    context-path: /api
  port: 8083

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    password: postgres
    username: postgres

microservices:
  product:
    url: http://localhost:8081/api
  user:
    url: http://localhost:8082/api
