CREATE TABLE IF NOT EXISTS carts (
    id bigserial PRIMARY KEY,
    user_id BIGSERIAL NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);